name: Node CI

on: [push, pull_request]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        fetch-depth: 100
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci
      run: |
        npm ci
      env:
        CI: true
    - name: npm build
      run: |
        npm run build
      env:
        CI: true
    - name: npm test
      run: |
        npm t
      env:
        CI: true
